name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "npm-cache"
      - name: Display Cache Output
        run: echo '${{ toJson(steps.cache-dependencies.outputs.cache-cache-hit) }}'
      - name: Install dependencies
        run: npm install
      - name: Use Axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhasdadjoke.com/', {
              headers: { Accept: 'text/plain' }
            });
            console.log(res.data)
