name: Checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -lsa
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -lsa
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -lsa
      - name: Checkout
        run: |
          git clone "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      - name: List Files After
        run: ls -lsa
