name: Concurrency 2
run-name: Concurrency 2 (${{ inputs.environment }})
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30