name: Concurrency 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment

concurrency: concurrency-1
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30