name: Concurrency 2
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30