name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
      # credentials:
      #   username: foo
      #   password: bar
      env:
        FOO: bar
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/container
      #   - /other/path
      #   - /path/in/host:/path/in/container
      # options: --cpus 1
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: 'echo "API_URL: $API_URL"'
      - name: Create a file
        run: echo 'Some text' > text.txt
      - name: Container in a Step
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Log node version
        uses: docker://node:slim
        with:
          args: -v

      - name: Show file contents
        uses: docker://node:slim
        with:
          entrypoint: cat
          args: text.txt

      - uses: actions/checkout@v4
      - name: Run a bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Your string here ;)"

      - name: Send a slack messgae
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "From Github Actions! :awesome-sunglasses:"
          SLACK_MESSAGE: "Actor: ${{ github.actor }}, Event: ${{ github.event_name }}"
          SLACK_COLOR: "#723fc4"