name: NPM Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Use Axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhasdadjoke.com/', {
              headers: { Accept: 'text/plain' }
            });
            console.log(res.data)
