name: Simple Action
on: [push]

jobs:
  simple-action:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simple JS Action
        id: greet
        uses: ./.github/actions/hello-docker
        with:
          whom_to_greet: Rambam
        # uses: actions/hello-world-javascript-action@v1
        # with:
        #   who-to-greet: Rambam
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Log ENV Var
        run: echo "HELLO_TIME = $HELLO_TIME"

  composite-action:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send a joke on Slack
        uses: ./.github/actions/slack-joke
        id: slack-joke
        with:
          slack_username: Rambam
          upload_joke: true
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Displaying joke output
        run: echo "${{ steps.slack-joke.outputs.joke }}"

  elaborate-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send a Slack Message
        uses: ./.github/actions/slack-php
        id: slack-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello there from PHP
