name: Stale issues & PRs
on:
  schedule:
    - cron: "*/3 * * * *"
    - cron: 29 17 * * *
    - cron: 27 15 * * *
    - cron: "*/5 15 * * *" # JUST FOR TESTING

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This is some message."
          days-before-stale: 1
          days-before-close: 5
