name: Stale issues & PRs
on:
  schedule:
    - cron: "*/9 * * * *"
    - cron: "17 17 * * *"
    - cron: "15 15 * * *" # JUST FOR TESTING

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This is some message by ${{ github.event.schedule }}."
          days-before-stale: 1
          days-before-close: 5
